main: ${project.package}.Main
name: ${project.name}

version: ${project.version}
description: ${project.description}
website: ${project.url}

authors:
  - CarmJos

api-version: 1.16

depend:
  - VotePass-Lobby

commands:
  "VotePassQQNotify":
    usage: "/VotePassQQNotify help"
    permission: "votepass.admin"