name: Build & Test

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK"
        uses: actions/setup-java@v5
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: "Package"
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload assets"
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: ".asset/*.jar"
          retention-days: 5
          include-hidden-files: true

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: "**/target/"
          retention-days: 1 # 仅保留1天。

          
