name: Build & Test

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Set up JDK"
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: "Package"
        run: mvn -B package --file pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: "**/target/"
          retention-days: 1 # 仅保留1天。

      - name: "Upload assets"
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: ".asset/"
          retention-days: 5